AWSTemplateFormatVersion: "2010-09-09"
Description:
  EBS Snapshot Notification settings

Parameters:
# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
# CloudWatchEvent名を指定
  CloudWatchEventName:
    Type: String

# SNSTopic名を指定
  TopicName:
    Type: String

# EBS Snapshotの完了通知を受信するEメールアドレスを指定
  Endpoint:
    Type: String

Resources:
# ------------------------------------------------------------# 
# CloudWatch Events Create
# ------------------------------------------------------------# 
  ConfigEventsRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: CloudWatch Ebents EBS Snapshot Configuration
      EventBusName: default
      EventPattern: 
        source: 
        - aws.ec2
        detail-type: 
        - 'EBS Snapshot Notification'

      Name: !Ref CloudWatchEventName
      State: ENABLED
      Targets: 
        -
          Arn: !Sub "arn:aws:sns:ap-northeast-1:${AWS::AccountId}:${ConfigSNSTopic.TopicName}"
          Id: !Ref TopicName

# ------------------------------------------------------------# 
# SNS Topic & Subscription Create
# ------------------------------------------------------------# 
  ConfigSNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        -
          Endpoint: !Ref Endpoint
          Protocol: email
      Tags: 
        -
          Key: Name
          Value: !Ref TopicName
      TopicName: !Ref TopicName
